### ISSUE TITLE
Confusing param :email

### ISSUE THREAD

**Issue by jennaleeb** [howtographql/graphql-ruby#7]
# Problem

In the ruby tutorial, the mutation for creating a user looks like 

```
class Resolvers::CreateUser < GraphQL::Function
  AuthProviderInput = GraphQL::InputObjectType.define do
    name 'AuthProviderSignupData'

    argument :email, Types::AuthProviderEmailInput
  end

  argument :name, !types.String
  argument :authProvider, !AuthProviderInput

  type Types::UserType

  def call(_obj, args, _ctx)
    User.create!(
      name: args[:name],
      email: args[:authProvider][:email][:email],
      password: args[:authProvider][:email][:password]
    )
  end
end
```

And creating a user looks like 

```
mutation {
  createUser(
    name: "some_name",
    authProvider: {
      email: {
        email: "some_email@email.com",
      	password: "1234"
      }
    }
  ) {
    id
    email
    name
  }
}
```

Since we are using the param `email` twice, it is easy to mistype the json if you aren't C/P-ing.

# Proposed solution

New to this but maybe something like `auth_input` ?

I can PR this @RStankov

**Comment by RStankov** [comment]
Hi @jennaleeb 

This is good suggestion. I think that `argument :authProvider, !AuthProviderInput` should be `argument :authProvider, !AuthProviderEmailInput` and skip the `[:email][:email]` altogether.

Unfortunately, the schema for the `graphql-ruby` tutorial should be the same as the rest of the "How to GraphQL" tutorials. So each backend can be used with each frontend.

Because of this, I can't change the schema design. 😒

**Comment by jennaleeb** [comment]
Ah I see, too bad! I made a few little notes as I was going through the tutorial, I'll PR them but take-it-or-leave-it. Great work BTW.

**Comment by chadoh** [comment]
@RStankov what was the reason for having the nested `[:email][:email]` nonsense in the API? It seems so weird and ugly to me, and throws off my whole learning process while reading this chapter. 

If it's not possible to improve the API (bummer), then maybe at least a sentence or two answering the question "why did we do it like that??" would be really helpful.

**Comment by nikolasburk** [comment]
Hey @chadoh!

As mentioned before, the reason for having this API design was to conform with the API of the frontend tutorials. *However*, the schema for the frontend tutorials have recently been updated as well, now using a much cleaner API for authentication (you can see the schema [here](https://github.com/howtographql/graphql-js/blob/master/src/schema.graphql)). Updates to all other backend tutorial tracks are planned soon! 🙌

**Comment by chadoh** [comment]
@nikolasburk looks much nicer! Great news!

Not sure how long it will take to implement the new backend tutorials. If it'll be a while, I think a short blurb in the chapter about Auth about _why it's being built that way_ would be really nice. Like, the tutorial just says "do this weird nested email thing" and pretends it's normal. And as a GraphQL newbie, I'm left scratching my head, wondering if it *IS* normal—f auth requests just _have_ to look super goofy in GraphQL. I have no idea where the line is between what's necessary and what's an odd implementation choice.

I don't want the reason listed to be "because someone else decided to design it that way a while ago idk." I want to hear what that someone else was thinking! What are the pros and cons of designing it the way it is? What are the other possibilities for what it could look like?

Authentication is complicated, and it seems like there's extra complexity added in for no reason here, and this complexity is never explained.
